### ISSUE TITLE
How to combine smime with SMTPMessage?

### ISSUE THREAD

**Issue by bbottema** [markenwerk/java-utils-mail-smime#8]
SMTPMessage is a subclass of MimeMessage, also provided by Java Mail, which provides some extra options.

How can I convert a signed MimeMessage into a SMTPMessage? The regular approach, gives an error with this library.
```java
MimeMessage m = new SMTPMessage(signedMimeMessage)
```
> nested exception is:
> 	java.io.IOException: net.markenwerk.utils.mail.dkim.DkimException: Incompatible version v=spf1 -all.
> 	at net.markenwerk.utils.mail.dkim.DkimSigner.sign(DkimSigner.java:424)
> 	at net.markenwerk.utils.mail.dkim.DkimMessage.writeTo(DkimMessage.java:116)
> 	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1887)
> 	at javax.mail.internet.MimeMessage.<init>(MimeMessage.java:252)
> 	at com.sun.mail.smtp.SMTPMessage.<init>(SMTPMessage.java:126)

**Comment by bbottema** [comment]
I think I'm mixing things up now. I've having an issue with DKIM signing, not S/MIME signing.

Still though, would be nice if this library supported SMTPMessages.
